# Generated by Django 5.1.7 on 2025-03-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='Question',
        ),
    ]
